// ============ THEME DEFINITIONS ============
// Based on market analysis of: Sleeper, Yahoo Fantasy, FanDuel, DraftKings,
// Dream11, Sorare, FPL, and modern UI trends

export interface StyleTheme {
  id: string
  name: string
  category: string
  description: string
  inspiration: string
  // Colors
  bg: string
  bgCard: string
  bgHover: string
  text: string
  textMuted: string
  textDim: string
  border: string
  primary: string
  primaryBg: string
  accent: string
  accentBg: string
  success: string
  danger: string
  gradient?: string
  special?: string
  // CSS variable values (hex colors)
  vars: {
    '--bg': string
    '--bg-card': string
    '--bg-hover': string
    '--text': string
    '--text-muted': string
    '--text-dim': string
    '--border': string
    '--primary': string
    '--primary-bg': string
    '--accent': string
    '--accent-bg': string
    '--success': string
    '--danger': string
  }
}

export const styleThemes: StyleTheme[] = [
  // ========== CATEGORIA 1: PREMIUM / LUXURY ==========
  {
    id: 'premium-gold',
    name: 'Premium Gold',
    category: 'Premium / Luxury',
    description: 'Tema scuro elegante con accenti dorati. Ideale per leghe premium e tornei esclusivi.',
    inspiration: 'Ispirato a DraftKings VIP e app di betting di lusso',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-amber-500 via-yellow-500 to-amber-600',
    vars: {
      '--bg': '#0a0a0f',
      '--bg-card': '#12121a',
      '--bg-hover': '#1a1a25',
      '--text': '#ffffff',
      '--text-muted': '#9ca3af',
      '--text-dim': '#4b5563',
      '--border': 'rgba(180, 83, 9, 0.3)',
      '--primary': '#fbbf24',
      '--primary-bg': 'rgba(245, 158, 11, 0.15)',
      '--accent': '#fcd34d',
      '--accent-bg': 'rgba(251, 191, 36, 0.1)',
      '--success': '#34d399',
      '--danger': '#f87171',
    },
  },
  {
    id: 'platinum-elite',
    name: 'Platinum Elite',
    category: 'Premium / Luxury',
    description: 'Design sofisticato con toni argento e blu ghiaccio. Per utenti esperti.',
    inspiration: 'Ispirato a app finanziarie premium e dashboard executive',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-slate-400 via-slate-300 to-slate-400',
    vars: {
      '--bg': '#0c0c12',
      '--bg-card': '#14141c',
      '--bg-hover': '#1c1c28',
      '--text': '#f1f5f9',
      '--text-muted': '#94a3b8',
      '--text-dim': '#475569',
      '--border': 'rgba(71, 85, 105, 0.4)',
      '--primary': '#cbd5e1',
      '--primary-bg': 'rgba(100, 116, 139, 0.15)',
      '--accent': '#38bdf8',
      '--accent-bg': 'rgba(14, 165, 233, 0.1)',
      '--success': '#2dd4bf',
      '--danger': '#fb7185',
    },
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    category: 'Premium / Luxury',
    description: 'Viola regale con tocchi dorati. Eleganza e prestigio per tornei importanti.',
    inspiration: 'Ispirato a brand sportivi di lusso e esports premium',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-purple-500 via-violet-500 to-purple-600',
    vars: {
      '--bg': '#0d0a14',
      '--bg-card': '#16121f',
      '--bg-hover': '#201a2d',
      '--text': '#faf5ff',
      '--text-muted': '#d8b4fe',
      '--text-dim': '#a855f7',
      '--border': 'rgba(107, 33, 168, 0.3)',
      '--primary': '#d8b4fe',
      '--primary-bg': 'rgba(168, 85, 247, 0.15)',
      '--accent': '#fbbf24',
      '--accent-bg': 'rgba(245, 158, 11, 0.1)',
      '--success': '#34d399',
      '--danger': '#f472b6',
    },
  },

  // ========== CATEGORIA 2: NEON / CYBERPUNK ==========
  {
    id: 'neon-cyber',
    name: 'Neon Cyber',
    category: 'Neon / Cyberpunk',
    description: 'Stile cyberpunk con neon cyan e magenta. Futuristico e audace.',
    inspiration: 'Ispirato a Sorare NFT e gaming esports',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-cyan-400 via-blue-500 to-fuchsia-500',
    special: 'shadow-[0_0_30px_rgba(0,255,255,0.15)]',
    vars: {
      '--bg': '#000000',
      '--bg-card': '#030712',
      '--bg-hover': '#111827',
      '--text': '#ecfeff',
      '--text-muted': '#67e8f9',
      '--text-dim': '#0891b2',
      '--border': 'rgba(6, 182, 212, 0.4)',
      '--primary': '#22d3ee',
      '--primary-bg': 'rgba(6, 182, 212, 0.2)',
      '--accent': '#e879f9',
      '--accent-bg': 'rgba(217, 70, 239, 0.2)',
      '--success': '#4ade80',
      '--danger': '#ef4444',
    },
  },
  {
    id: 'electric-pink',
    name: 'Electric Pink',
    category: 'Neon / Cyberpunk',
    description: 'Rosa elettrico su nero profondo. Energico e distintivo.',
    inspiration: 'Ispirato a UI gaming moderne e stream overlay',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-pink-500 via-rose-500 to-fuchsia-500',
    vars: {
      '--bg': '#050507',
      '--bg-card': '#0d0d12',
      '--bg-hover': '#15151f',
      '--text': '#fdf2f8',
      '--text-muted': '#f9a8d4',
      '--text-dim': '#db2777',
      '--border': 'rgba(236, 72, 153, 0.3)',
      '--primary': '#f472b6',
      '--primary-bg': 'rgba(236, 72, 153, 0.2)',
      '--accent': '#a78bfa',
      '--accent-bg': 'rgba(139, 92, 246, 0.15)',
      '--success': '#a3e635',
      '--danger': '#f87171',
    },
  },
  {
    id: 'matrix-green',
    name: 'Matrix Green',
    category: 'Neon / Cyberpunk',
    description: 'Verde Matrix su nero. Tech-inspired per appassionati di dati.',
    inspiration: 'Ispirato a dashboard di analytics e tech interfaces',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-green-400 via-emerald-500 to-green-600',
    vars: {
      '--bg': '#020804',
      '--bg-card': '#071208',
      '--bg-hover': '#0c1a0f',
      '--text': '#f0fdf4',
      '--text-muted': '#4ade80',
      '--text-dim': '#15803d',
      '--border': 'rgba(34, 197, 94, 0.3)',
      '--primary': '#4ade80',
      '--primary-bg': 'rgba(34, 197, 94, 0.15)',
      '--accent': '#6ee7b7',
      '--accent-bg': 'rgba(16, 185, 129, 0.1)',
      '--success': '#a3e635',
      '--danger': '#ef4444',
    },
  },

  // ========== CATEGORIA 3: SPORTS / ATHLETIC ==========
  {
    id: 'stadium-blue',
    name: 'Stadium Blue',
    category: 'Sports / Athletic',
    description: 'Blu stadio classico. Professionale e sportivo come le grandi app.',
    inspiration: 'Ispirato a Yahoo Fantasy e ESPN',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-blue-500 via-blue-600 to-indigo-600',
    vars: {
      '--bg': '#0a1628',
      '--bg-card': '#0f1e33',
      '--bg-hover': '#152840',
      '--text': '#ffffff',
      '--text-muted': '#93c5fd',
      '--text-dim': '#3b82f6',
      '--border': 'rgba(37, 99, 235, 0.3)',
      '--primary': '#60a5fa',
      '--primary-bg': 'rgba(59, 130, 246, 0.2)',
      '--accent': '#facc15',
      '--accent-bg': 'rgba(234, 179, 8, 0.15)',
      '--success': '#34d399',
      '--danger': '#f87171',
    },
  },
  {
    id: 'champions-red',
    name: 'Champions Red',
    category: 'Sports / Athletic',
    description: 'Rosso campioni dinamico. Passione e competizione.',
    inspiration: 'Ispirato a brand sportivi come Liverpool, Man United',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-red-500 via-red-600 to-rose-600',
    vars: {
      '--bg': '#120808',
      '--bg-card': '#1a0c0c',
      '--bg-hover': '#241212',
      '--text': '#fef2f2',
      '--text-muted': '#fca5a5',
      '--text-dim': '#ef4444',
      '--border': 'rgba(153, 27, 27, 0.4)',
      '--primary': '#f87171',
      '--primary-bg': 'rgba(239, 68, 68, 0.2)',
      '--accent': '#fbbf24',
      '--accent-bg': 'rgba(245, 158, 11, 0.15)',
      '--success': '#34d399',
      '--danger': '#fb923c',
    },
  },
  {
    id: 'pitch-green',
    name: 'Pitch Green',
    category: 'Sports / Athletic',
    description: 'Verde campo da calcio. Autentico e immersivo.',
    inspiration: 'Ispirato a FPL e app calcistiche europee',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-emerald-500 via-green-600 to-emerald-700',
    vars: {
      '--bg': '#0a1a0f',
      '--bg-card': '#0f2415',
      '--bg-hover': '#152e1c',
      '--text': '#ecfdf5',
      '--text-muted': '#6ee7b7',
      '--text-dim': '#059669',
      '--border': 'rgba(4, 120, 87, 0.3)',
      '--primary': '#34d399',
      '--primary-bg': 'rgba(16, 185, 129, 0.2)',
      '--accent': '#ffffff',
      '--accent-bg': 'rgba(255, 255, 255, 0.1)',
      '--success': '#a3e635',
      '--danger': '#f87171',
    },
  },

  // ========== CATEGORIA 4: MINIMALIST / CLEAN ==========
  {
    id: 'clean-white',
    name: 'Clean White',
    category: 'Minimalist / Clean',
    description: 'Design pulito e luminoso. Massima leggibilita e professionalita.',
    inspiration: 'Ispirato a Apple e design scandinavo',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    vars: {
      '--bg': '#f9fafb',
      '--bg-card': '#ffffff',
      '--bg-hover': '#f3f4f6',
      '--text': '#111827',
      '--text-muted': '#4b5563',
      '--text-dim': '#9ca3af',
      '--border': '#e5e7eb',
      '--primary': '#2563eb',
      '--primary-bg': '#eff6ff',
      '--accent': '#4f46e5',
      '--accent-bg': '#eef2ff',
      '--success': '#059669',
      '--danger': '#dc2626',
    },
  },
  {
    id: 'soft-gray',
    name: 'Soft Gray',
    category: 'Minimalist / Clean',
    description: 'Grigio morbido elegante. Neutro e rilassante per lunghe sessioni.',
    inspiration: 'Ispirato a Notion e app productivity',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    vars: {
      '--bg': '#f5f5f4',
      '--bg-card': '#ffffff',
      '--bg-hover': '#fafaf9',
      '--text': '#292524',
      '--text-muted': '#78716c',
      '--text-dim': '#a8a29e',
      '--border': '#e7e5e4',
      '--primary': '#44403c',
      '--primary-bg': '#f5f5f4',
      '--accent': '#d97706',
      '--accent-bg': '#fffbeb',
      '--success': '#059669',
      '--danger': '#dc2626',
    },
  },
  {
    id: 'paper-cream',
    name: 'Paper Cream',
    category: 'Minimalist / Clean',
    description: 'Toni crema caldi. Confortevole come carta stampata.',
    inspiration: 'Ispirato a app di lettura e design editoriale',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    vars: {
      '--bg': '#faf8f5',
      '--bg-card': '#ffffff',
      '--bg-hover': '#f5f3f0',
      '--text': '#292524',
      '--text-muted': '#78716c',
      '--text-dim': '#a8a29e',
      '--border': '#e7e5e4',
      '--primary': '#b45309',
      '--primary-bg': '#fffbeb',
      '--accent': '#ea580c',
      '--accent-bg': '#fff7ed',
      '--success': '#047857',
      '--danger': '#b91c1c',
    },
  },

  // ========== CATEGORIA 5: GRADIENT / MODERN ==========
  {
    id: 'aurora-gradient',
    name: 'Aurora Gradient',
    category: 'Gradient / Modern',
    description: 'Gradienti aurora boreale. Moderno e accattivante.',
    inspiration: 'Ispirato a Stripe e design fintech moderno',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-violet-500 via-fuchsia-500 to-pink-500',
    vars: {
      '--bg': '#0f172a',
      '--bg-card': 'rgba(30, 41, 59, 0.8)',
      '--bg-hover': 'rgba(51, 65, 85, 0.6)',
      '--text': '#ffffff',
      '--text-muted': '#cbd5e1',
      '--text-dim': '#64748b',
      '--border': 'rgba(71, 85, 105, 0.3)',
      '--primary': '#a78bfa',
      '--primary-bg': 'rgba(139, 92, 246, 0.2)',
      '--accent': '#f472b6',
      '--accent-bg': 'rgba(236, 72, 153, 0.15)',
      '--success': '#34d399',
      '--danger': '#f87171',
    },
  },
  {
    id: 'sunset-blend',
    name: 'Sunset Blend',
    category: 'Gradient / Modern',
    description: 'Sfumature calde del tramonto. Accogliente e dinamico.',
    inspiration: 'Ispirato a Instagram e social media moderni',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-orange-500 via-rose-500 to-pink-500',
    vars: {
      '--bg': '#18181b',
      '--bg-card': 'rgba(39, 39, 42, 0.9)',
      '--bg-hover': 'rgba(63, 63, 70, 0.7)',
      '--text': '#fff7ed',
      '--text-muted': '#fed7aa',
      '--text-dim': '#fb923c',
      '--border': 'rgba(194, 65, 12, 0.3)',
      '--primary': '#fb923c',
      '--primary-bg': 'rgba(249, 115, 22, 0.2)',
      '--accent': '#fb7185',
      '--accent-bg': 'rgba(244, 63, 94, 0.15)',
      '--success': '#facc15',
      '--danger': '#f87171',
    },
  },
  {
    id: 'ocean-wave',
    name: 'Ocean Wave',
    category: 'Gradient / Modern',
    description: 'Blu oceano profondo con sfumature acqua. Fluido e rilassante.',
    inspiration: 'Ispirato a app wellness e design marino',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-cyan-500 via-blue-500 to-teal-500',
    vars: {
      '--bg': '#0f172a',
      '--bg-card': 'rgba(30, 41, 59, 0.8)',
      '--bg-hover': 'rgba(51, 65, 85, 0.6)',
      '--text': '#ecfeff',
      '--text-muted': '#67e8f9',
      '--text-dim': '#06b6d4',
      '--border': 'rgba(8, 145, 178, 0.3)',
      '--primary': '#22d3ee',
      '--primary-bg': 'rgba(6, 182, 212, 0.2)',
      '--accent': '#2dd4bf',
      '--accent-bg': 'rgba(20, 184, 166, 0.15)',
      '--success': '#34d399',
      '--danger': '#fb7185',
    },
  },

  // ========== CATEGORIA 6: DARK PROFESSIONAL ==========
  {
    id: 'sleeper-dark',
    name: 'Sleeper Dark',
    category: 'Dark Professional',
    description: 'Tema scuro bilanciato. Ispirato alla migliore app fantasy USA.',
    inspiration: 'Direttamente ispirato a Sleeper App',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    vars: {
      '--bg': '#1a1d24',
      '--bg-card': '#23272f',
      '--bg-hover': '#2c313a',
      '--text': '#ffffff',
      '--text-muted': '#9ca3af',
      '--text-dim': '#6b7280',
      '--border': 'rgba(55, 65, 81, 0.4)',
      '--primary': '#4ade80',
      '--primary-bg': 'rgba(34, 197, 94, 0.15)',
      '--accent': '#60a5fa',
      '--accent-bg': 'rgba(59, 130, 246, 0.15)',
      '--success': '#34d399',
      '--danger': '#f87171',
    },
  },
  {
    id: 'draftkings-style',
    name: 'DraftKings Style',
    category: 'Dark Professional',
    description: 'Verde DraftKings su nero. Riconoscibile e professionale.',
    inspiration: 'Ispirato a DraftKings Fantasy',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    vars: {
      '--bg': '#0d0d0d',
      '--bg-card': '#1a1a1a',
      '--bg-hover': '#252525',
      '--text': '#ffffff',
      '--text-muted': '#9ca3af',
      '--text-dim': '#4b5563',
      '--border': '#1f2937',
      '--primary': '#53d337',
      '--primary-bg': 'rgba(83, 211, 55, 0.15)',
      '--accent': '#ffffff',
      '--accent-bg': 'rgba(255, 255, 255, 0.1)',
      '--success': '#4ade80',
      '--danger': '#ef4444',
    },
  },
  {
    id: 'fanduel-blue',
    name: 'FanDuel Blue',
    category: 'Dark Professional',
    description: 'Blu FanDuel distintivo. Affidabile e competitivo.',
    inspiration: 'Ispirato a FanDuel Fantasy',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    vars: {
      '--bg': '#0c1929',
      '--bg-card': '#132238',
      '--bg-hover': '#1a2d47',
      '--text': '#ffffff',
      '--text-muted': '#bfdbfe',
      '--text-dim': '#60a5fa',
      '--border': 'rgba(30, 64, 175, 0.4)',
      '--primary': '#1493ff',
      '--primary-bg': 'rgba(20, 147, 255, 0.2)',
      '--accent': '#fb923c',
      '--accent-bg': 'rgba(249, 115, 22, 0.15)',
      '--success': '#34d399',
      '--danger': '#f87171',
    },
  },

  // ========== CATEGORIA 7: PLAYFUL / FUN ==========
  {
    id: 'candy-pop',
    name: 'Candy Pop',
    category: 'Playful / Fun',
    description: 'Colori vivaci e giocosi. Perfetto per leghe tra amici.',
    inspiration: 'Ispirato a Duolingo e app gaming casual',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-yellow-400 via-pink-500 to-violet-500',
    vars: {
      '--bg': '#2e1065',
      '--bg-card': 'rgba(76, 29, 149, 0.8)',
      '--bg-hover': 'rgba(109, 40, 217, 0.6)',
      '--text': '#ffffff',
      '--text-muted': '#ddd6fe',
      '--text-dim': '#a78bfa',
      '--border': 'rgba(124, 58, 237, 0.4)',
      '--primary': '#facc15',
      '--primary-bg': 'rgba(234, 179, 8, 0.2)',
      '--accent': '#f472b6',
      '--accent-bg': 'rgba(236, 72, 153, 0.2)',
      '--success': '#a3e635',
      '--danger': '#fb923c',
    },
  },
  {
    id: 'tropical-vibes',
    name: 'Tropical Vibes',
    category: 'Playful / Fun',
    description: 'Colori tropicali brillanti. Estate e divertimento tutto lanno.',
    inspiration: 'Ispirato a brand lifestyle e travel',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    gradient: 'from-cyan-400 via-teal-500 to-orange-400',
    vars: {
      '--bg': '#042f2e',
      '--bg-card': 'rgba(17, 94, 89, 0.8)',
      '--bg-hover': 'rgba(20, 184, 166, 0.6)',
      '--text': '#ffffff',
      '--text-muted': '#99f6e4',
      '--text-dim': '#2dd4bf',
      '--border': 'rgba(13, 148, 136, 0.4)',
      '--primary': '#22d3ee',
      '--primary-bg': 'rgba(6, 182, 212, 0.2)',
      '--accent': '#fb923c',
      '--accent-bg': 'rgba(249, 115, 22, 0.2)',
      '--success': '#a3e635',
      '--danger': '#f472b6',
    },
  },

  // ========== CATEGORIA 8: GLASSMORPHISM ==========
  {
    id: 'glass-dark',
    name: 'Glass Dark',
    category: 'Glassmorphism',
    description: 'Effetto vetro su sfondo scuro. Moderno e sofisticato.',
    inspiration: 'Ispirato a Apple Vision Pro e UI moderne',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    special: 'backdrop-blur-xl',
    vars: {
      '--bg': '#0f0f14',
      '--bg-card': 'rgba(255, 255, 255, 0.05)',
      '--bg-hover': 'rgba(255, 255, 255, 0.1)',
      '--text': '#ffffff',
      '--text-muted': '#d1d5db',
      '--text-dim': '#6b7280',
      '--border': 'rgba(255, 255, 255, 0.1)',
      '--primary': '#60a5fa',
      '--primary-bg': 'rgba(59, 130, 246, 0.2)',
      '--accent': '#a78bfa',
      '--accent-bg': 'rgba(139, 92, 246, 0.15)',
      '--success': '#34d399',
      '--danger': '#f87171',
    },
  },
  {
    id: 'frosted-blue',
    name: 'Frosted Blue',
    category: 'Glassmorphism',
    description: 'Vetro smerigliato su blu. Elegante e tecnologico.',
    inspiration: 'Ispirato a Windows 11 e design Microsoft',
    bg: 'bg-theme-bg',
    bgCard: 'bg-theme-card',
    bgHover: 'bg-theme-hover',
    text: 'text-theme-text',
    textMuted: 'text-theme-muted',
    textDim: 'text-theme-dim',
    border: 'border-theme-border',
    primary: 'text-theme-primary',
    primaryBg: 'bg-theme-primary-bg',
    accent: 'text-theme-accent',
    accentBg: 'bg-theme-accent-bg',
    success: 'text-theme-success',
    danger: 'text-theme-danger',
    special: 'backdrop-blur-xl',
    vars: {
      '--bg': '#1e3a5f',
      '--bg-card': 'rgba(255, 255, 255, 0.1)',
      '--bg-hover': 'rgba(255, 255, 255, 0.15)',
      '--text': '#ffffff',
      '--text-muted': '#dbeafe',
      '--text-dim': '#93c5fd',
      '--border': 'rgba(255, 255, 255, 0.2)',
      '--primary': '#67e8f9',
      '--primary-bg': 'rgba(6, 182, 212, 0.2)',
      '--accent': '#ffffff',
      '--accent-bg': 'rgba(255, 255, 255, 0.15)',
      '--success': '#6ee7b7',
      '--danger': '#fda4af',
    },
  },
]

// Font definitions
export const fonts = {
  system: { name: 'System', desc: 'Font di sistema', value: 'system-ui, -apple-system, sans-serif' },
  inter: { name: 'Inter', desc: 'Moderno e leggibile', value: 'Inter, system-ui, sans-serif' },
  roboto: { name: 'Roboto', desc: 'Google Material', value: 'Roboto, system-ui, sans-serif' },
  poppins: { name: 'Poppins', desc: 'Geometrico', value: 'Poppins, system-ui, sans-serif' },
  mono: { name: 'Mono', desc: 'Monospazio', value: 'ui-monospace, monospace' },
}

export type FontKey = keyof typeof fonts

// Get unique categories
export const themeCategories = [...new Set(styleThemes.map(t => t.category))]

// Default theme
export const DEFAULT_THEME_ID = 'sleeper-dark'
export const DEFAULT_FONT: FontKey = 'system'
